# Generated by Django 4.1.4 on 2022-12-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=50)),
                ('CustomerPhoneNo', models.IntegerField()),
                ('CustomerMail', models.EmailField(max_length=254)),
                ('CustomerAddress', models.CharField(max_length=450)),
            ],
        ),
    ]
