# Generated by Django 4.1.5 on 2023-01-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=50)),
                ('CustomerPhoneNo', models.IntegerField()),
                ('CustomerEMail', models.EmailField(max_length=254)),
                ('CustomerAddress', models.CharField(max_length=450)),
                ('Status', models.CharField(default='active', max_length=50)),
                ('Notes', models.TextField(default=' ', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_ID', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('M_R_P', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Units', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='media/')),
                ('Status', models.CharField(max_length=50)),
                ('Notes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_ID', models.IntegerField()),
                ('EMP_Name', models.CharField(max_length=254)),
                ('Email', models.EmailField(max_length=254)),
                ('D_O_B', models.DateField()),
                ('Qualifiaction', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=350)),
                ('Role', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
                ('Join_date', models.DateField()),
                ('Status', models.CharField(max_length=50)),
                ('Notess', models.TextField()),
            ],
        ),
    ]
