# Generated by Django 4.1.4 on 2022-12-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_ID', models.IntegerField()),
                ('EMP_Name', models.CharField(max_length=254)),
                ('Email', models.EmailField(max_length=254)),
                ('D_O_B', models.DateField()),
                ('Qualifiaction', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=350)),
                ('Role', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
                ('Join_date', models.DateField()),
                ('Status', models.CharField(max_length=50)),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='Notes',
            field=models.TextField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='customer',
            name='Status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
