# Generated by Django 4.1.4 on 2022-12-31 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_service', '0002_staff_customer_notes_customer_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Notes',
            new_name='Notess',
        ),
    ]
