# Generated by Django 4.1.4 on 2022-12-31 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_service', '0003_rename_notes_staff_notess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='CustomerMail',
            new_name='CustomerEMail',
        ),
    ]
