# Generated by Django 4.1.4 on 2023-01-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_service', '0004_rename_customermail_customer_customeremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_ID', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('M_R_P', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Units', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='media/product')),
                ('Status', models.CharField(max_length=50)),
                ('Notes', models.CharField(max_length=50)),
            ],
        ),
    ]
