# Generated by Django 4.1.4 on 2023-01-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_service', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
